spring:
  cors:
    allowed-origins: "chrome-extension://pfdhoblngboilpfeibdedpjgfnlcodoo"
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://healthhivedb.cpceyykqk0vx.ap-south-1.rds.amazonaws.com:3306/Health-Hive?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:healthhive_admin}
    password: ${JDBC_DATABASE_PASSWORD:health_hiveuom}
    dbcp2:
      max-wait-millis: 30000
      validation-query: /* ping */ select 1
      validation-query-timeout: 30

#   security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-hh:8080/realms/Health-Hive
          jwk-set-uri: http://keycloak-hh:8080/realms/Health-Hive/protocol/openid-connect/certs




  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  docker:
    compose:
      lifecycle-management: start-only

jwt:
  auth:
    converter:
      resource-id : health-hive-client
      principal-attribute: principal_username



logging:
  level:
    org:
      springframework:
        security: DEBUG
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      UserEmailUnique: USER_EMAIL_UNIQUE
      LabRequestUserUnique: LAB_REQUEST_USER_UNIQUE
      LabRequestLabUnique: LAB_REQUEST_LAB_UNIQUE
      LabReportSharePatientUnique: LAB_REPORT_SHARE_PATIENT_UNIQUE
      LabReportShareDoctorUnique: LAB_REPORT_SHARE_DOCTOR_UNIQUE

springdoc:
  pathsToMatch: /api/**

server:
  port: 33000

file:
  upload-dir: C:\Users\uvher\OneDrive\Documents\HealthHiveBackend\healthhive\src\test\resources

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.hibernate: DEBUG
#    org.springframework.web.cors: DEBUG
#temp


