global:
  scrape_interval: 60s
  evaluation_interval: 60s

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "rule.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
      - targets: ['nginx-prometheus-exporter:9113']

  - job_name: 'keycloak'
    scrape_interval: 5s
    static_configs:
      - targets: ['keycloak-hh:8080']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-hp-exporter:9104'] # Replace 'mysql_host' with your MySQL container hostname/IP

